[book]
authors = ["Jake"]
language = "en"
multilingual = false
src = "docs"
title = "FnCtl"

[build]
build-dir = "book"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors

