name: "flake"
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths: [".github/workflows/flake.yml", "flake.nix", "flake.lock", "*.nix"]
  pull_request:
    branches: [main]
    paths: [".github/workflows/flake.yml", "flake.nix", "flake.lock", "*.nix"]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Initialize our flake.nix
      run: nix flake lock && nix flake prefetch
    - name: Show all inputs to flake.nix
      run: nix flake metadata 
    - name: Show all outputs from flake.nix
      run: nix flake show 2>/dev/null